# Step 1: Use Node for building
FROM node:18 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build

# Step 2: Use Nginx for serving the built app
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80 to host
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
